version: "3.8"
services:
  backend:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    networks:
      - my-network
    environment:
      DB_USER: issuesUser
      DB_PASSWORD: securePassword123
      DB_NAME: issues

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - my-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongodb_data:/data/db # Persist MongoDB data
      - ./mongo-init:/docker-entrypoint-initdb.d # Run init script

networks:
  my-network:
    driver: bridge

volumes:
  mongodb_data:
